# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrimeMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrimeMap
	pod 'Parse'
 	pod 'AlamofireImage'

  target 'CrimeMapTests' do
    # Pods for testing
  end

  target 'CrimeMapUITests' do
    # Pods for testing
  end

end
